# fly.toml file generated for segora-client on 2023-04-10T01:01:05+08:00

app = "segora-client"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  BACKEND_HOST = "https://segora-services.fly.dev"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
